CREATE TYPE acc_type AS ENUM ('uim', 'hcim', 'im', 'reg');

CREATE TABLE stats_pit (
  stats_id SERIAL,
  created_at timestamp DEFAULT now(),
  is_latest boolean DEFAULT TRUE,
  
  ign varchar(12),
  acc_type acc_type,
  is_p2p boolean,

  total_level decimal DEFAULT 0,
  total_exp decimal DEFAULT 0,
  total_rank decimal DEFAULT -1,
  att_level decimal DEFAULT 0,
  att_exp decimal DEFAULT 0,
  att_rank decimal DEFAULT -1,
  def_level decimal DEFAULT 0,
  def_exp decimal DEFAULT 0,
  def_rank decimal DEFAULT -1,
  str_level decimal DEFAULT 0,
  str_exp decimal DEFAULT 0,
  str_rank decimal DEFAULT -1,
  hp_level decimal DEFAULT 0,
  hp_exp decimal DEFAULT 0,
  hp_rank decimal DEFAULT -1,
  range_level decimal DEFAULT 0,
  range_exp decimal DEFAULT 0,
  range_rank decimal DEFAULT -1,
  pray_level decimal DEFAULT 0,
  pray_exp decimal DEFAULT 0,
  pray_rank decimal DEFAULT -1,
  mage_level decimal DEFAULT 0,
  mage_exp decimal DEFAULT 0,
  mage_rank decimal DEFAULT -1,
  cook_level decimal DEFAULT 0,
  cook_exp decimal DEFAULT 0,
  cook_rank decimal DEFAULT -1,
  wc_level decimal DEFAULT 0,
  wc_exp decimal DEFAULT 0,
  wc_rank decimal DEFAULT -1,
  fish_level decimal DEFAULT 0,
  fish_exp decimal DEFAULT 0,
  fish_rank decimal DEFAULT -1,
  fm_level decimal DEFAULT 0,
  fm_exp decimal DEFAULT 0,
  fm_rank decimal DEFAULT -1,
  craft_level decimal DEFAULT 0,
  craft_exp decimal DEFAULT 0,
  craft_rank decimal DEFAULT -1,
  mining_level decimal DEFAULT 0,
  mining_exp decimal DEFAULT 0,
  mining_rank decimal DEFAULT -1,
  smith_level decimal DEFAULT 0,
  smith_exp decimal DEFAULT 0,
  smith_rank decimal DEFAULT -1,
  rc_level decimal DEFAULT 0,
  rc_exp decimal DEFAULT 0,
  rc_rank decimal DEFAULT -1,

  obor_kc decimal DEFAULT 0,
  obor_rank decimal DEFAULT -1,
  bryo_kc decimal DEFAULT 0,
  bryo_rank decimal DEFAULT -1,
  clue decimal DEFAULT 0,
  clue_rank decimal DEFAULT -1,
  lms decimal DEFAULT 0,
  lms_rank decimal DEFAULT -1,
  
  primary key (stats_id)
);

CREATE VIEW ranks AS
  SELECT
    ign,
    DENSE_RANK() OVER (ORDER BY total_exp DESC) as total_rank,
    DENSE_RANK() OVER (ORDER BY att_exp DESC) as att_rank,
    DENSE_RANK() OVER (ORDER BY def_exp DESC) as def_rank,
    DENSE_RANK() OVER (ORDER BY str_exp DESC) as str_rank,
    DENSE_RANK() OVER (ORDER BY hp_exp DESC) as hp_rank,
    DENSE_RANK() OVER (ORDER BY range_exp DESC) as range_rank,
    DENSE_RANK() OVER (ORDER BY pray_exp DESC) as pray_rank,
    DENSE_RANK() OVER (ORDER BY mage_exp DESC) as mage_rank,
    DENSE_RANK() OVER (ORDER BY cook_exp DESC) as cook_rank,
    DENSE_RANK() OVER (ORDER BY wc_exp DESC) as wc_rank,
    DENSE_RANK() OVER (ORDER BY fish_exp DESC) as fish_rank,
    DENSE_RANK() OVER (ORDER BY fm_exp DESC) as fm_rank,
    DENSE_RANK() OVER (ORDER BY craft_exp DESC) as craft_rank,
    DENSE_RANK() OVER (ORDER BY mining_exp DESC) as mining_rank,
    DENSE_RANK() OVER (ORDER BY smith_exp DESC) as smith_rank,
    DENSE_RANK() OVER (ORDER BY rc_exp DESC) as rc_rank,
    DENSE_RANK() OVER (ORDER BY obor_kc DESC) as obor_rank,
    DENSE_RANK() OVER (ORDER BY bryo_kc DESC) as bryo_rank,
    DENSE_RANK() OVER (ORDER BY clue DESC) as clue_rank,
    DENSE_RANK() OVER (ORDER BY lms DESC) as lms_rank
  FROM stats_pit
  WHERE
    is_latest IS TRUE;
