version: "3.1"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:9.5.3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  redis:
    image: "redis:5.0.13"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

volumes:
  pgdata:
  redisdata:
